/**
 * The widget presets the channel editor offers.
 *
 * Many entries repeat the same `data` / `widgetData` / `dimensions` blocks verbatim,
 * so those are declared once here and called per entry. Each builder returns a fresh
 * object: `renderer-v2` reads entries straight out of this table without cloning, so a
 * shared instance would let one widget mutate another.
 */

const dataPreset = () => ({
  url: '',
  posterImage: '',
  subtitles: [],
  autoplay: false,
  markers: [],
  resumePoint: 0,
  setCookie: false,
  disableTelemetry: false,
})

const dataPreset2 = () => [
  {
    banners: { l: '', m: '', s: '', xl: '', xs: '' },
    redirectUrl: '',
    title: '',
    openInNewTab: true,
  },
]

const dataPreset3 = () => ({
  videoData: {},
  externalData: {},
})

const dataPreset4 = () => ({
  type: 'text',
  html: '',
  template: '',
  templateUrl: '',
  templateData: undefined,
  templateDataUrl: '',
  containerStyle: {
    padding: '10px',
    overflow: 'hidden',
    'word-wrap': 'break-word',
    'box-sizing': 'border-box',
  },
  containerClass: 'mat-elevation-z4 h-full w-full',
})

const widgetDataPreset = () => ({
  html: '',
  type: 'set1',
  template: '',
  templateUrl: '',
  templateData: undefined,
  templateDataUrl: '',
  containerStyle: { 'box-sizing': ' border-box' },
  containerClass: 'mat-elevation-z4 h-full w-full',
})

const widgetDataPreset2 = () => ({
  type: 'image',
  subType: 'set1',
  designVal: 'set2',
  autoNext: false,
  delay: 0,
  loop: false,
  cardMenu: [
    {
      cardData: {},
      widget: {
        widgetSubType: 'elementHtml',
        widgetType: 'element',
        widgetHostClass: '',
        widgetHostStyle: {},
        widgetData: {
          html: '',
          type: 'set1',
          template: '',
          templateUrl: '',
          templateData: undefined,
          templateDataUrl: '',
          containerStyle: { 'box-sizing': ' border-box' },
          containerClass: 'h-full w-full',
        },
      },
    },
  ],
  configs: {
    widgetPlayer: {},
    widgetRibbon: {},
  },
})

const widgetDataPreset3 = () => ({
  type: 'video',
  designVal: 'set2',
  autoNext: false,
  delay: 0,
  loop: false,
  cardMenu: [
    {
      cardData: {},
      widget: {
        widgetType: 'player',
        widgetSubType: 'playerVideo',
        data: {
          url: '',
          posterImage: '',
          subtitles: [],
          autoplay: false,
          markers: [],
          resumePoint: 0,
          setCookie: false,
          disableTelemetry: false,
        },
        widgetHostClass: '',
        widgetHostStyle: {},
      },
    },
  ],
  configs: {
    widgetPlayer: {},
    widgetRibbon: {},
  },
})

const widgetDataPreset4 = () => ({
  type: 'iframe',
  designVal: 'set2',
  autoNext: false,
  delay: 0,
  loop: false,
  cardMenu: [
    {
      cardData: {},
      widget: {
        widgetData: { iframeSrc: '', title: '' },
        widgetSubType: 'pageEmbedded',
        widgetType: 'page',
      },
    },
  ],
  configs: {
    widgetPlayer: {},
    widgetRibbon: {},
  },
})

const widgetDataPreset5 = () => ({
  type: 'imageMap',
  selectFrom: [
    {
      minWidth: 0,
      maxWidth: 500090000,
      widget: {
        widgetData: {
          map: [],
        },
        widgetSubType: 'imageMapResponsive',
        widgetType: 'imageMap',
        widgetHostClass: '',
      },
    },
  ],
})

const dataPreset5 = () => ({
  isIntranet: {
    widget: {
      widgetData: {
        iframeSrc: '',
        containerStyle: { 'min-height': '400px' },
      },
      widgetSubType: 'pageEmbedded',
      widgetType: 'page',
      widgetHostClass: '',
    },
  },
  isNotIntranet: {
    widget: {
      widgetData: {
        template:
          "<div class='w-full'><div class='p-4'><div class='text-3xl font-semibold text-center leading-tight'>{{title}}</div><br /><div class='text-base font-medium text-center leding-normal'>{{subheading}}</div></div></div>",
        templateData: {
          title: 'Content not available online',
          subheading: 'You can view this on intranet only.Please connect to intranet to view this.',
        },
        containerClass: 'mat-elevation-z4 h-full flex bg-gray-400',
        containerStyle: { 'align-items': 'center' },
      },
      widgetSubType: 'elementHtml',
      widgetType: 'element',
      widgetHostClass: '',
    },
  },
})

const dataPreset6 = () => ({
  html: '',
  template: '',
  templateUrl: '',
  templateData: undefined,
  templateDataUrl: '',
  containerStyle: { overflow: 'hidden', 'word-wrap': 'break-word', 'box-sizing': 'border-box' },
  containerClass: 'h-full w-full',
})

const widgetDataPreset6 = () => ({
  type: 'image',
  subType: 'set1',
  selectFrom: [
    {
      minWidth: 0,
      maxWidth: 500090000,
      widget: {
        widgetSubType: 'elementHtml',
        widgetType: 'element',
        widgetHostClass: '',
        widgetHostStyle: {},
        widgetData: {
          html: '',
          type: 'set1',
          template: '',
          templateUrl: '',
          templateData: undefined,
          templateDataUrl: '',
          containerStyle: { 'box-sizing': ' border-box' },
          containerClass: 'h-full w-full',
        },
      },
    },
  ],
})

const widgetDataPreset7 = () => ({
  type: 'video',
  designVal: 'set2',
  autoNext: false,
  delay: 0,
  loop: false,
  cardMenu: [
    {
      cardData: {},
      widget: {
        widgetType: 'wrapper',
        widgetSubType: 'videoWrapper',
        widgetData: {
          videoData: {},
          externalData: {},
        },
        widgetHostClass: '',
        widgetHostStyle: {},
      },
    },
  ],
  configs: {
    widgetPlayer: {},
    widgetRibbon: {},
  },
})

const widgetDataPreset8 = () => ({
  url: '',
  posterImage: '',
  subtitles: [],
  autoplay: false,
  markers: [],
  resumePoint: 0,
  setCookie: false,
  disableTelemetry: false,
})

export const WIDGET_LIBRARY = {
  audio: {
    widgetType: 'player',
    widgetSubType: 'playerAudio',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '100%', width: '100%' },
  },
  one_audio: {
    widgetType: 'player',
    widgetSubType: 'playerAudio',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_audio: {
    widgetType: 'player',
    widgetSubType: 'playerAudio',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_audio: {
    widgetType: 'player',
    widgetSubType: 'playerAudio',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '994px' },
    dimensions: { small: 12, medium: 6, large: 9, xLarge: 9 },
  },
  four_audio: {
    widgetType: 'player',
    widgetSubType: 'playerAudio',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  video: {
    widgetType: 'player',
    widgetSubType: 'playerVideo',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '100%', width: '100%' },
  },
  one_video: {
    widgetType: 'player',
    widgetSubType: 'playerVideo',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_video: {
    widgetType: 'player',
    widgetSubType: 'playerVideo',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_video: {
    widgetType: 'player',
    widgetSubType: 'playerVideo',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 6, large: 9, xLarge: 9 },
  },
  four_video: {
    widgetType: 'player',
    widgetSubType: 'playerVideo',
    data: dataPreset(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  html: {
    data: {
      html: '',
      template: '',
      templateUrl: '',
      templateData: undefined,
      templateDataUrl: '',
      containerStyle: {},
      containerClass: '',
    },
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: {},
  },
  slider: { widgetType: 'slider', widgetSubType: 'sliderBanners', data: dataPreset2() },
  one_slider: {
    widgetType: 'slider',
    widgetSubType: 'sliderBanners',
    data: dataPreset2(),
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_slider: {
    widgetType: 'slider',
    widgetSubType: 'sliderBanners',
    data: dataPreset2(),
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_slider: {
    widgetType: 'slider',
    widgetSubType: 'sliderBanners',
    data: dataPreset2(),
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_slider: {
    widgetType: 'slider',
    widgetSubType: 'sliderBanners',
    data: dataPreset2(),
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  iframe: { data: { iframeSrc: '', title: '' }, widgetSubType: 'pageEmbedded', widgetType: 'page' },
  one_iframe: {
    data: { iframeSrc: '', title: '' },
    widgetSubType: 'pageEmbedded',
    widgetType: 'page',
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
    widgetHostStyle: { height: '472px', width: '331px' },
  },
  two_iframe: {
    data: { iframeSrc: '', title: '' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
    widgetHostStyle: { height: '472px', width: '662px' },
    widgetSubType: 'pageEmbedded',
    widgetType: 'page',
  },
  three_iframe: {
    data: { iframeSrc: '', title: '' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
    widgetHostStyle: { height: '472px', width: '993px' },
    widgetSubType: 'pageEmbedded',
    widgetType: 'page',
  },
  four_iframe: {
    data: { iframeSrc: '', title: '' },
    widgetHostStyle: { height: '472px', width: '1324px' },
    widgetSubType: 'pageEmbedded',
    widgetType: 'page',
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  breadcrum: {
    data: {
      path: [
        { clickUrl: '/author/cbp/me', text: 'Home' },
        { clickUrl: '', text: 'Add Path...' },
      ],
    },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
    widgetSubType: 'cardBreadcrumb',
    widgetType: 'card',
    widgetHostClass: 'block',
    widgetHostStyle: { 'box-sizing': 'border-box' },
  },
  solo_iframe: { widgetData: { iframeSrc: '', title: '' }, widgetSubType: 'pageEmbedded', widgetType: 'page' },
  solo_video: {
    widgetType: 'player',
    widgetSubType: 'playerVideo',
    widgetData: widgetDataPreset8(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
  },
  solo_audio: {
    widgetType: 'player',
    widgetSubType: 'playerAudio',
    widgetData: widgetDataPreset8(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
  },
  solo_image: {
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: {},
    widgetData: {
      html: '',
      type: 'set1',
      template: '',
      templateUrl: '',
      templateData: undefined,
      templateDataUrl: '',
      containerStyle: { 'box-sizing': ' border-box' },
      containerClass: 'h-full w-full',
    },
  },
  solo_map: {
    widgetData: {
      imageHeight: 0,
      imageWidth: 0,
      imageSrc: '',
      mapName: '',
      map: [],
      externalData: '',
      containerStyle: {},
      containerClass: '',
    },
    widgetSubType: 'imageMapResponsive',
    widgetType: 'imageMap',
    widgetHostClass: '',
    widgetHostStyle: {},
  },
  map: {
    data: {
      imageHeight: 0,
      imageWidth: 0,
      imageSrc: '',
      mapName: '',
      map: [],
      externalData: '',
      containerStyle: {},
      containerClass: '',
    },
    widgetSubType: 'imageMapResponsive',
    widgetType: 'imageMap',
    widgetHostClass: '',
    widgetHostStyle: {},
  },
  selector: {
    data: {},
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: {},
  },
  strip: {
    data: {},
    widgetSubType: 'contentStripMultiple',
    widgetType: 'contentStrip',
    widgetHostClass: '',
    widgetHostStyle: {},
  },
  strip_single: {
    data: {},
    widgetSubType: 'contentStripSingle',
    widgetType: 'contentStrip',
    widgetHostClass: '',
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  gallery: {
    data: {
      designVal: 'set1',
      autoNext: false,
      delay: 0,
      loop: false,
      configs: {
        widgetPlayer: {},
        widgetRibbon: {},
      },
    },
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: {},
  },
  empty: { data: {}, widgetSubType: '', widgetType: '' },
  one_html: {
    data: {
      html: '',
      template: '',
      templateUrl: '',
      templateData: undefined,
      templateDataUrl: '',
      containerStyle: { 'box-sizing': ' border-box', overflow: 'hidden', 'word-wrap': 'break-word' },
      containerClass: 'h-full w-full',
    },
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_html: {
    data: dataPreset6(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_html: {
    data: dataPreset6(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_html: {
    data: dataPreset6(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_text: {
    data: dataPreset4(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_text: {
    data: dataPreset4(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_text: {
    data: dataPreset4(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_text: {
    data: dataPreset4(),
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  title: {
    data: {
      type: 'title',
      template: '<h1 class="mat-h1 inline-block">{{title}}</h1>',
      templateData: { title: 'Title' },
      containerStyle: {},
      containerClass: 'h-full',
    },
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: 'block -mb-16',
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_image: {
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    widgetData: widgetDataPreset(),
  },
  two_image: {
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    widgetData: widgetDataPreset(),
  },
  three_image: {
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    widgetData: widgetDataPreset(),
  },
  four_image: {
    widgetSubType: 'elementHtml',
    widgetType: 'element',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    widgetData: widgetDataPreset(),
  },
  one_resp_image: {
    widgetData: {
      type: 'image',
      subType: 'set1',
      selectFrom: [
        {
          minWidth: 0,
          maxWidth: 500090000,
          widget: {
            widgetSubType: 'elementHtml',
            widgetType: 'element',
            widgetHostClass: '',
            widgetHostStyle: {},
            widgetData: {
              html: '',
              type: 'set1',
              template: '',
              templateUrl: '',
              templateData: undefined,
              templateDataUrl: '',
              containerStyle: { 'box-sizing': ' border-box' },
              containerClass: 'h-full w-full',
            },
          },
          widgetSubType: 'imageMapResponsive',
          widgetType: 'imageMap',
          widgetHostClass: '',
          widgetHostStyle: {},
        },
      ],
    },
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_resp_image: {
    widgetData: widgetDataPreset6(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_resp_image: {
    widgetData: widgetDataPreset6(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 6, large: 9, xLarge: 9 },
  },
  four_resp_image: {
    widgetData: widgetDataPreset6(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_gallery_image: {
    widgetData: widgetDataPreset2(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_gallery_image: {
    widgetData: widgetDataPreset2(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_gallery_image: {
    widgetData: widgetDataPreset2(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_gallery_image: {
    widgetData: widgetDataPreset2(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_gallery_video: {
    widgetData: widgetDataPreset3(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_gallery_video: {
    widgetData: widgetDataPreset3(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_gallery_video: {
    widgetData: widgetDataPreset3(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_gallery_video: {
    widgetData: widgetDataPreset3(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_gallery_iframe: {
    widgetData: widgetDataPreset4(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_gallery_iframe: {
    widgetData: widgetDataPreset4(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_gallery_iframe: {
    widgetData: widgetDataPreset4(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_gallery_iframe: {
    widgetData: widgetDataPreset4(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_strip: {
    data: {},
    widgetSubType: 'contentStripMultiple',
    widgetType: 'contentStrip',
    widgetHostClass: '',
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_strip: {
    data: {},
    widgetSubType: 'contentStripMultiple',
    widgetType: 'contentStrip',
    widgetHostClass: '',
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_strip: {
    data: {},
    widgetSubType: 'contentStripMultiple',
    widgetType: 'contentStrip',
    widgetHostClass: '',
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 6, large: 9, xLarge: 9 },
  },
  four_strip: {
    data: {},
    widgetSubType: 'contentStripMultiple',
    widgetType: 'contentStrip',
    widgetHostClass: '',
    widgetHostStyle: {},
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  one_resp_map: {
    widgetData: widgetDataPreset5(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_resp_map: {
    widgetData: widgetDataPreset5(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_resp_map: {
    widgetData: widgetDataPreset5(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 6, large: 9, xLarge: 9 },
  },
  four_resp_map: {
    widgetData: widgetDataPreset5(),
    widgetSubType: 'selectorResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  wrapper: {
    widgetType: 'wrapper',
    widgetSubType: 'videoWrapper',
    data: dataPreset3(),
    widgetHostClass: '',
    widgetHostStyle: { height: '100%', width: '100%' },
  },
  one_wrapper: {
    widgetType: 'wrapper',
    widgetSubType: 'videoWrapper',
    data: dataPreset3(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_wrapper: {
    widgetType: 'wrapper',
    widgetSubType: 'videoWrapper',
    data: dataPreset3(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_wrapper: {
    widgetType: 'wrapper',
    widgetSubType: 'videoWrapper',
    data: dataPreset3(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 6, large: 9, xLarge: 9 },
  },
  four_wrapper: {
    widgetType: 'wrapper',
    widgetSubType: 'videoWrapper',
    data: dataPreset3(),
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  gallery_wrapper: {
    widgetData: {
      type: 'video',
      designVal: 'set2',
      autoNext: true,
      delay: '',
      loop: true,
      cardMenu: [
        {
          cardData: {},
          widget: {
            widgetType: 'wrapper',
            widgetSubType: 'videoWrapper',
            widgetData: {
              videoData: {},
              externalData: {},
            },
            widgetHostClass: '',
            widgetHostStyle: {},
          },
        },
      ],
      configs: {
        widgetPlayer: {},
        widgetRibbon: {},
      },
    },
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '100%', width: '100%' },
  },
  one_gallery_wrapper: {
    widgetData: {
      type: 'video',
      designVal: 'set2',
      autoNext: true,
      delay: 10,
      loop: true,
      cardMenu: [
        {
          cardData: {},
          widget: {
            widgetType: 'wrapper',
            widgetSubType: 'videoWrapper',
            widgetData: {
              videoData: {},
              externalData: {},
            },
            widgetHostClass: '',
            widgetHostStyle: {},
          },
        },
      ],
      configs: {
        widgetPlayer: {},
        widgetRibbon: {},
      },
    },
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_gallery_wrapper: {
    widgetData: widgetDataPreset7(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '662px' },
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_gallery_wrapper: {
    widgetData: widgetDataPreset7(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '993px' },
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_gallery_wrapper: {
    widgetData: widgetDataPreset7(),
    widgetSubType: 'galleryView',
    widgetType: 'gallery',
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '1324px' },
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
  solo_wrapper: {
    widgetType: 'wrapper',
    widgetSubType: 'videoWrapper',
    widgetData: {
      videoData: {},
      externalData: {},
    },
    widgetHostClass: '',
    widgetHostStyle: { height: '472px', width: '331px' },
  },
  one_intranet: {
    widgetSubType: 'intranetResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: {},
    data: dataPreset5(),
    dimensions: { small: 12, medium: 6, large: 3, xLarge: 3 },
  },
  two_intranet: {
    widgetSubType: 'intranetResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: {},
    data: dataPreset5(),
    dimensions: { small: 12, medium: 12, large: 6, xLarge: 6 },
  },
  three_intranet: {
    widgetSubType: 'intranetResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: {},
    data: dataPreset5(),
    dimensions: { small: 12, medium: 12, large: 9, xLarge: 9 },
  },
  four_intranet: {
    widgetSubType: 'intranetResponsive',
    widgetType: 'selector',
    widgetHostClass: '',
    widgetHostStyle: {},
    data: dataPreset5(),
    dimensions: { small: 12, medium: 12, large: 12, xLarge: 12 },
  },
}
