import { of } from 'rxjs'

import { SearchServService } from './search-serv.service'

/**
 * Wave 18 — the filter transformation of SearchServService: `searchV6Wrapper`'s
 * optional request fields, `handleFilters` and `getDisplayName`.
 */
describe('SearchServService (filters)', () => {
  let service: SearchServService
  let events: any
  let searchApi: any
  let configSrv: any
  let http: any

  beforeEach(() => {
    localStorage.clear()
    events = { dispatchEvent: jest.fn() }
    searchApi = {
      getSearchAutoCompleteResults: jest.fn().mockReturnValue(of([])),
      getSearchV6Results: jest.fn().mockReturnValue(of({ result: [] })),
      getSearchResults: jest.fn().mockReturnValue(of({ result: [] })),
    }
    configSrv = { sitePath: '/site', activeOrg: 'o1', rootOrg: 'r1' }
    http = { get: jest.fn().mockReturnValue(of({ search: { visibleFilters: {}, excludeSourceFields: [] } })) }
    service = new SearchServService(events, searchApi, configSrv, http)
  })

  // ------------------------------------------------------- searchV6Wrapper --

  describe('searchV6Wrapper', () => {
    const sent = () => searchApi.getSearchV6Results.mock.calls[0][0]

    it('carries the paging and filters through', () => {
      service
        .searchV6Wrapper({
          locale: ['en'],
          pageNo: 2,
          pageSize: 20,
          query: 'maths',
          filters: { contentType: ['Course'] },
        } as any)
        .subscribe()
      expect(sent()).toEqual(
        expect.objectContaining({
          locale: ['en'],
          pageNo: 2,
          pageSize: 20,
          query: 'maths',
          includeSourceFields: ['creatorLogo'],
        }),
      )
      expect(sent().filters[0].andFilters).toEqual([{ contentType: ['Course'] }])
    })

    it('leaves paging unset when it was not asked for', () => {
      service.searchV6Wrapper({ locale: ['en'], query: '', pageNo: 0, pageSize: 0 } as any).subscribe()
      expect(sent().pageNo).toBeUndefined()
      expect(sent().pageSize).toBeUndefined()
    })

    it('sends no filters when none were given', () => {
      service.searchV6Wrapper({ locale: ['en'], query: '' } as any).subscribe()
      expect(sent().filters[0].andFilters).toEqual([])
    })

    it('passes the stand-alone flag through when present', () => {
      service.searchV6Wrapper({ locale: ['en'], query: '', isStandAlone: true } as any).subscribe()
      expect(sent().isStandAlone).toBe(true)
    })

    it('leaves the stand-alone flag unset when absent', () => {
      service.searchV6Wrapper({ locale: ['en'], query: '' } as any).subscribe()
      expect(sent().isStandAlone).toBeUndefined()
    })
  })

  // ------------------------------------------------------------ getDisplayName --

  describe('getDisplayName', () => {
    it.each([
      ['automationCentral', 'Tools'],
      ['autoGeneratedTopic', 'Topics'],
      ['topics', 'Topics'],
      ['kshopDocument', 'Kshop Document'],
      ['project', 'Project References'],
      ['kshop', 'Documents'],
      ['itemType', 'Item Type'],
      ['authors.mailId', 'Authors'],
      ['mstLocation', 'Location'],
      ['status', 'Project Status'],
      ['marketing', 'Marketing'],
    ])('renames %s to %s', (type, expected) => {
      expect(service.getDisplayName(type)).toBe(expected)
    })

    it('leaves an unrecognised type alone', () => {
      expect(service.getDisplayName('contentType')).toBe('contentType')
    })
  })

  // ---------------------------------------------------------- handleFilters --

  describe('handleFilters', () => {
    const filterUnit = (over: any = {}) => ({
      type: 'contentType',
      displayName: 'Content type',
      content: [
        { type: 'Course', displayName: 'Course', children: [] },
        { type: 'Resource', displayName: 'Resource', children: [] },
      ],
      ...over,
    })

    /** handleFilters takes the flattened selection set alongside the raw selection. */
    const run = (filters: any[], selected: any = {}, showContentType?: boolean) => {
      const { filterSet } = service.updateSelectedFiltersSet(selected)
      return service.handleFilters(filters as any, filterSet, selected, showContentType)
    }

    it('ticks the facet the learner has selected', () => {
      const { filtersRes } = run([filterUnit()], { contentType: ['Course'] })
      expect(filtersRes[0].checked).toBe(true)
      expect(filtersRes[0].content[0].checked).toBe(true)
      expect(filtersRes[0].content[1].checked).toBe(false)
    })

    it('leaves every facet unticked with no selection', () => {
      const { filtersRes } = run([filterUnit()], {})
      expect(filtersRes[0].checked).toBe(false)
      expect(filtersRes[0].content[0].checked).toBe(false)
    })

    it('drops the last-modified facet', () => {
      const { filtersRes } = run([filterUnit({ type: 'dtLastModified' })], {})
      expect(filtersRes).toEqual([])
    })

    it('drops the content-type facet when the caller hides it', () => {
      const { filtersRes } = run([filterUnit()], {}, true)
      expect(filtersRes).toEqual([])
    })

    it('keeps the content-type facet by default', () => {
      const { filtersRes } = run([filterUnit()], {}, false)
      expect(filtersRes).toHaveLength(1)
    })

    it('ticks a selected second-level facet', () => {
      const nested = filterUnit({
        content: [{ type: 'Course', displayName: 'Course', children: [{ type: 'Basic', displayName: 'Basic' }] }],
      })
      const { filtersRes } = run([nested], { contentType: ['Basic'] })
      expect(filtersRes[0].content[0].children[0].checked).toBe(true)
    })

    it('gives a leaf facet an empty child list', () => {
      const { filtersRes } = run([filterUnit({ content: [{ type: 'Course', displayName: 'Course' }] })], {})
      expect(filtersRes[0].content[0].children).toEqual([])
    })
  })

  // ------------------------------------------------- updateSelectedFiltersSet --

  describe('updateSelectedFiltersSet', () => {
    it('collects every selected value into one set', () => {
      const { filterSet, filterReset } = service.updateSelectedFiltersSet({
        contentType: ['Course', 'Resource'],
        lang: ['en'],
      })
      expect(filterSet.has('Course')).toBe(true)
      expect(filterSet.has('en')).toBe(true)
      expect(filterReset).toBe(true)
    })

    it('reports nothing to reset when every facet is empty', () => {
      const { filterSet, filterReset } = service.updateSelectedFiltersSet({ contentType: [] })
      expect(filterSet.size).toBe(0)
      expect(filterReset).toBe(false)
    })

    it('expands a tag path into each of its levels', () => {
      const { filterSet } = service.updateSelectedFiltersSet({ tags: ['health/immunisation/basic'] })
      expect(filterSet.has('health')).toBe(true)
      expect(filterSet.has('health/immunisation')).toBe(true)
      expect(filterSet.has('health/immunisation/basic')).toBe(true)
    })

    it('handles being given nothing at all', () => {
      const { filterSet } = service.updateSelectedFiltersSet(undefined as any)
      expect(filterSet.size).toBe(0)
    })
  })

  // ------------------------------------------------- transformSearchV6Filters --

  describe('transformSearchV6Filters', () => {
    it('flattens the and-filter groups into one map', () => {
      expect(
        service.transformSearchV6Filters([
          { andFilters: [{ contentType: ['Course'] }, { lang: ['en'] }] },
          { andFilters: [{ status: ['Live'] }] },
        ] as any),
      ).toEqual({ contentType: ['Course'], lang: ['en'], status: ['Live'] })
    })

    it('ignores a group with no and-filters', () => {
      expect(service.transformSearchV6Filters([{}] as any)).toEqual({})
    })
  })
})
